import React from "react";
import Login from "./Login";

export const metadata = {
  title: "Login TaskVista",
  description: "Generated by The Ninjan | Niranjan Solanki",
};

function LoginPage() {
  return <Login />;
}

export default LoginPage;
