import React from "react";
import ShowTasks from "./ShowTasks";
export const metadata = {
title: "TaskVista",
description: "Generated by The Ninjan | Niranjan Solanki",
};
const ShowTasksPage = () => {
  return <ShowTasks />;
};

export default ShowTasksPage;
