import React from "react";
import Signup from "./Signup";

export const metadata = {
  title: "Signup : TaskVista",
  description: "Generated by The Ninjan | Niranjan Solanki",
};

const SignUpPage = () => {
  return <Signup />;
};

export default SignUpPage;
